name: Test
on: [push, pull_request]
jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x,18.x]
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm t
